Document: libapache2-mod-ox
Title: Debian libapache2-mod-ox Manual
Author: <insert document author here>
Abstract: This manual describes what libapache2-mod-ox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libapache2-mod-ox/libapache2-mod-ox.sgml.gz

Format: postscript
Files: /usr/share/doc/libapache2-mod-ox/libapache2-mod-ox.ps.gz

Format: text
Files: /usr/share/doc/libapache2-mod-ox/libapache2-mod-ox.text.gz

Format: HTML
Index: /usr/share/doc/libapache2-mod-ox/html/index.html
Files: /usr/share/doc/libapache2-mod-ox/html/*.html
